### ISSUE TITLE
Zero-shot setting questions

### ISSUE THREAD

**Issue by hangzhiyiwei** [mrwu-mac/EoID#11]
Hi @jxgu1016  thank you for your excellent work

I have some questions about the zero-shot settings. I wonder what is the definition of the zero-shot settings. Only the HOI annotations are masked but all the images are available? In this case, is it more like semi-supervised learning in your case, because your method needs those images without unseen labels for training? 

I also find that you provide all possible HOI phrases (seen+unseen) into the CLIP text encoder, so I just get a little bit confused about the definition of the zero-shot setting.

Thank you very much.

**Comment by mrwu-mac** [comment]
Thank you for your interest in our work.

We aim to use large-scale object detection data to further scale up the action sets. So, we adopt a transductive zero-shot setting in our work, which the all images and gt boxes are available.

**Comment by hangzhiyiwei** [comment]
Thank you for your reply. 

I find that for object detection, the zero-shot setting means that the unseen class images are not available and only the descriptions can be used for the model to do classification. They aim to discover more objects with only text information.

Then in the HOI zero-shot detection, what is the key point of the zero-shot? We can have unseen HOI labels and images with unseen HOI classes, but they are not matched. Is this the case?

**Comment by mrwu-mac** [comment]
We can detect all the objects in the image, but we don't know whether there is an interaction between the human-object pairs, and also the verb categories for the potential interactive pairs.

**Comment by hangzhiyiwei** [comment]
Thanks very much. Got your point.

I also wonder whether all the zero-shot HOI detection methods are the same setting as yours or not. Is it a general benchmark that the model can access the images with unseen HOI classes and their GT Bboxes for training?

**Comment by mrwu-mac** [comment]
As far as I know, there may be some subtle differences between our work and previous works. Most of the previous works use the object detector which pre-trained on COCO 80-categories object detection dataset. On the HOI detection datasets, they remove the samples(either images or unseen pairs) containing the unseen HOI categories.

**Comment by hangzhiyiwei** [comment]
Understand. Thank you for your reply very much!
