### ISSUE TITLE
consistency_graph.pkl

### ISSUE THREAD

**Issue by JingyuLi-code** [mrwu-mac/EoID#13]
Can you share consistency_graph.pkl files?

**Comment by mrwu-mac** [comment]
You can get it from [ConsNet](https://github.com/yeliudev/ConsNet). We do not keep this file because it wasn't relevant to our main work.

**Comment by JingyuLi-code** [comment]
When we run ConsNet,  we get this error. Do you have any ideas?
![image](https://github.com/mrwu-mac/EoID/assets/45377489/3baf9cf1-6154-4d3c-a8f4-ae32f40880fe)
