### ISSUE TITLE
implementation details

### ISSUE THREAD

**Issue by liuc-v** [mrwu-mac/EoID#16]
Thank you for your inspiring work!!
I have a small question. Do you use any prior information in your work when inferring the HOI category or action category? For example, one object can only correspond to a subset of actions. Can we set the probabilities of other actions to zero in the post-processing stage?

**Comment by mrwu-mac** [comment]
Yes, you are right, we use prior information as mentioned in Sec 4.3 in the paper. And also set the probabilities of other actions to zero in the post-processing stage following previous works.

**Comment by liuc-v** [comment]
Thanks for your reply!
I still have a question: Should the prior information be modified in the settings for training the UC or UA, compared to the default mode?Then, during the reasoning process, the prior information is changed to be the same as the default mode.

**Comment by mrwu-mac** [comment]
In the zero-set setting, the prior information does not need to be modified, either during training or testing.

**Comment by liuc-v** [comment]
Thanks you really helped me a lot.
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        1/29/2024 14:16
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [mrwu-mac/EoID] implementation details (Issue #16)
        
      
    
  

In the zero-set setting, the prior information does not need to be modified, either during training or testing.

**Comment by liuc-v** [comment]
M

**Comment by liuc-v** [comment]
May I ask where is the corresponding code that you use the prior information.

**Comment by mrwu-mac** [comment]
The prior information as defined in `datasets/static_hico.py`, you can find the corresponding code in the dataset and model.

**Comment by liuc-v** [comment]
Thanks
