### ISSUE TITLE
About removing 'no interaction' class

### ISSUE THREAD

**Issue by maoyunyao** [mrwu-mac/EoID#8]
Hi! Thanks for your great work and the released code~

I have a small question as to why the no-interaction category is masked here.

https://github.com/mrwu-mac/EoID/blob/6bc11d5821fd9a6be2f47e571eb4d57f81284095/datasets/hico_ua_st_v1.py#L182

**Comment by mrwu-mac** [comment]
The no-interaction mask is used to train the Interactive Score module, which is used to distinguish interactive and non-interactive pairs.

**Comment by maoyunyao** [comment]
Got it! Thanks~
