### ISSUE TITLE
confusion in hico_uc_st and hico_ua_st_v1

### ISSUE THREAD

**Issue by PradKalkar** [mrwu-mac/EoID#9]
Hi. I was trying to understand the code for hico_uc_st.py and hico_ua_st_v1.py. I am confused about a line of code in these two files.
Please refer to the line where seen_mask is defined (line 53 in hico_uc_st.py). In this, the seen_mask is set to 1 for all the verb ids. In UC, all the actions are seen. But, when I saw the lines 52 and 53 in hico_ua_st_v1.py, there 1 was assigned in the seen_mask to only unseen actions and 0 for seen actions. So, could you please explain why the behaviour of seen_mask is opposite for UC and UA settings?

https://github.com/mrwu-mac/EoID/blob/6bc11d5821fd9a6be2f47e571eb4d57f81284095/datasets/hico_uc_st.py#L53
https://github.com/mrwu-mac/EoID/blob/6bc11d5821fd9a6be2f47e571eb4d57f81284095/datasets/hico_ua_st_v1.py#L52
https://github.com/mrwu-mac/EoID/blob/6bc11d5821fd9a6be2f47e571eb4d57f81284095/datasets/hico_ua_st_v1.py#L53

**Comment by mrwu-mac** [comment]
For UC setting, we distill knowledge of all actions; 
For UA setting, only unseen actions.

**Comment by PradKalkar** [comment]
Got it. Thanks!
